### PR TITLE
Copy attributes from source field to target

### PR DESCRIPTION
**Pull request by ahijevyc**
Use copy_atts module. Call after target fields are defined.
This is done in convert_mpas.F.

### CODE REVIEW

**Comment by ahijevyc** [comment]
I would like to use convert_mpas for TC tracking.  My version isn't as user-friendly or well-written but it copies attributes from the source field to the target field.  I thought I'd offer this capability to convert_mpas.  Possibly global attributes too.  

I love this new GitHub thing. Let me know if I violate best practice.

**Comment by mgduda** [comment]
This looks like a really nice addition to the code. In `src/Makefile`, I think there are some dependencies that we'll need for the new `copy_atts.o` object file. The `copy_atts` module depends on the `scan_input`, `file_output`, and `remapper` modules, and without these dependencies explicitly given in the Makefile, builds may fail (for example, try a parallel build with `make -j 4`). So, I'd propose adding
```
copy_atts.o: scan_input.o file_output.o remapper.o
```
in `src/Makefile`.

**Comment by ahijevyc** [comment]
Thanks!  I will do that.

**Comment by ahijevyc** [comment]
Now I understand a little more about Makefiles.

I added copy_atts.o decendencies to src/Makefile, committed, and pushed to
my GitHub.  Do I have to do anything else? I expected to need a new pull
request, but maybe not.

Dave

**Comment by mgduda** [comment]
GitHub uses branch names for pull requests (rather than a particular commit hash), so pushing changes to a branch automatically updates a PR. This makes it really easy to update a PR when a reviewer requests any sort of modifications to the contents of a PR.

The changes to the `Makefile` look good -- I'll fast-forward merge into the `master` branch. Thanks, again!

**Comment by ahijevyc** [comment]
What about global attributes? I could easily add those. 

Dave

**Comment by mgduda** [comment]
If it would be helpful for your work, I see no problem at all with adding global attributes as well. In that case, it may be cleanest to bring in those changes through a new PR, since this one has already been marked as "Merged".

**Pull request merged**
